[2025-02-25T00:41:10.008+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-25T00:41:10.029+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:36:02.502236+00:00 [queued]>
[2025-02-25T00:41:10.036+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:36:02.502236+00:00 [queued]>
[2025-02-25T00:41:10.037+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 6
[2025-02-25T00:41:10.051+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_bronze> on 2025-02-25 00:36:02.502236+00:00
[2025-02-25T00:41:10.058+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=476) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-25T00:41:10.060+0000] {standard_task_runner.py:63} INFO - Started process 478 to run task
[2025-02-25T00:41:10.060+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_bronze', 'upload_bronze', 'manual__2025-02-25T00:36:02.502236+00:00', '--job-id', '52', '--raw', '--subdir', 'DAGS_FOLDER/Dag_des_5.py', '--cfg-path', '/tmp/tmp6tk5p6kb']
[2025-02-25T00:41:10.062+0000] {standard_task_runner.py:91} INFO - Job 52: Subtask upload_bronze
[2025-02-25T00:41:10.128+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:36:02.502236+00:00 [running]> on host c37e8af922b1
[2025-02-25T00:41:10.220+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_bronze' AIRFLOW_CTX_TASK_ID='upload_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:36:02.502236+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T00:36:02.502236+00:00'
[2025-02-25T00:41:10.222+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-25T00:41:10.223+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-25T00:41:10.224+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app/upload_bronze.py", line 12, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\RID-156732_Desafio08\\Airflow\\dags\\app\\Dados'
[2025-02-25T00:41:10.244+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_bronze, task_id=upload_bronze, execution_date=20250225T003602, start_date=20250225T004110, end_date=20250225T004110
[2025-02-25T00:41:10.260+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 52 for task upload_bronze ([Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\RID-156732_Desafio08\\Airflow\\dags\\app\\Dados'; 478)
[2025-02-25T00:41:10.277+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-25T00:41:10.307+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-25T00:41:10.310+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
