[2025-02-16T01:09:42.036+0000] {processor.py:161} INFO - Started process (PID=3238) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:09:42.040+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:09:42.045+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:09:42.041+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:09:42.165+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:09:42.150+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:09:42.171+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:09:42.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.210 seconds
[2025-02-16T01:10:12.665+0000] {processor.py:161} INFO - Started process (PID=3297) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:12.673+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:10:12.674+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:10:12.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:12.709+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:10:12.704+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:10:12.711+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:12.739+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.090 seconds
[2025-02-16T01:10:43.187+0000] {processor.py:161} INFO - Started process (PID=3357) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:43.188+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:10:43.190+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:10:43.189+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:43.235+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:10:43.226+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:10:43.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:10:43.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.089 seconds
[2025-02-16T01:11:13.747+0000] {processor.py:161} INFO - Started process (PID=3417) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:13.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:11:13.749+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:11:13.749+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:13.780+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:11:13.776+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:11:13.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:15.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 1.640 seconds
[2025-02-16T01:11:46.293+0000] {processor.py:161} INFO - Started process (PID=3478) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:46.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:11:46.296+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:11:46.296+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:46.346+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:11:46.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:11:46.348+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:11:46.372+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.086 seconds
[2025-02-16T01:12:16.710+0000] {processor.py:161} INFO - Started process (PID=3538) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:16.712+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:12:16.713+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:12:16.713+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:16.744+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:12:16.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:12:16.746+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:16.767+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.063 seconds
[2025-02-16T01:12:47.202+0000] {processor.py:161} INFO - Started process (PID=3598) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:47.203+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:12:47.205+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:12:47.204+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:47.235+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:12:47.232+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:12:47.237+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:12:47.256+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.063 seconds
[2025-02-16T01:13:17.348+0000] {processor.py:161} INFO - Started process (PID=3658) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:17.349+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:13:17.350+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:13:17.350+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:17.426+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:13:17.388+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:13:17.429+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:17.462+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.124 seconds
[2025-02-16T01:13:47.720+0000] {processor.py:161} INFO - Started process (PID=3718) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:47.721+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:13:47.723+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:13:47.722+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:47.764+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:13:47.760+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:13:47.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:13:47.785+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.072 seconds
[2025-02-16T01:14:17.864+0000] {processor.py:161} INFO - Started process (PID=3778) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:17.865+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:14:17.866+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:14:17.866+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:17.902+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:14:17.898+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:14:17.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:17.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.069 seconds
[2025-02-16T01:14:47.987+0000] {processor.py:161} INFO - Started process (PID=3838) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:47.988+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:14:47.990+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:14:47.989+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:48.024+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:14:48.019+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:14:48.026+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:14:48.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:15:18.148+0000] {processor.py:161} INFO - Started process (PID=3898) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:18.149+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:15:18.151+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:15:18.150+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:18.190+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:15:18.186+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:15:18.192+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:18.214+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.073 seconds
[2025-02-16T01:15:48.442+0000] {processor.py:161} INFO - Started process (PID=3958) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:48.443+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:15:48.444+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:15:48.444+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:48.481+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:15:48.476+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:15:48.482+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:15:48.505+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.070 seconds
[2025-02-16T01:16:19.037+0000] {processor.py:161} INFO - Started process (PID=4018) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:19.038+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:16:19.039+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:16:19.039+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:19.084+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:16:19.077+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:16:19.086+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:19.110+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.081 seconds
[2025-02-16T01:16:49.715+0000] {processor.py:161} INFO - Started process (PID=4078) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:49.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:16:49.717+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:16:49.717+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:49.753+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:16:49.749+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:16:49.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:16:49.780+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.071 seconds
[2025-02-16T01:17:19.910+0000] {processor.py:161} INFO - Started process (PID=4138) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:19.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:17:19.913+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:17:19.913+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:19.972+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:17:19.960+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:17:19.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:20.032+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.130 seconds
[2025-02-16T01:17:50.295+0000] {processor.py:161} INFO - Started process (PID=4198) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:50.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:17:50.298+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:17:50.298+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:50.331+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:17:50.327+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:17:50.333+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:17:50.835+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.547 seconds
[2025-02-16T01:18:21.457+0000] {processor.py:161} INFO - Started process (PID=4258) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:21.458+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:18:21.459+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:18:21.459+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:21.505+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:18:21.502+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:18:21.507+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:21.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.082 seconds
[2025-02-16T01:18:51.952+0000] {processor.py:161} INFO - Started process (PID=4318) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:51.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:18:51.955+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:18:51.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:51.994+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:18:51.990+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:18:51.995+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:18:52.016+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.070 seconds
[2025-02-16T01:19:22.567+0000] {processor.py:161} INFO - Started process (PID=4384) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:22.568+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:19:22.569+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:19:22.569+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:22.601+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:19:22.597+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:19:22.602+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:22.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.064 seconds
[2025-02-16T01:19:53.143+0000] {processor.py:161} INFO - Started process (PID=4445) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:53.145+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:19:53.146+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:19:53.146+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:53.178+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:19:53.174+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:19:53.180+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:19:53.201+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.064 seconds
[2025-02-16T01:20:23.668+0000] {processor.py:161} INFO - Started process (PID=4505) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:23.669+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:20:23.671+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:20:23.670+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:23.704+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:20:23.700+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:20:23.705+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:23.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.065 seconds
[2025-02-16T01:20:54.181+0000] {processor.py:161} INFO - Started process (PID=4565) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:54.182+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:20:54.183+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:20:54.183+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:54.218+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:20:54.213+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:20:54.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:20:54.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.067 seconds
[2025-02-16T01:21:24.500+0000] {processor.py:161} INFO - Started process (PID=4625) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:24.502+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:21:24.504+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:21:24.504+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:24.537+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:21:24.533+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:21:24.538+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:24.558+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.064 seconds
[2025-02-16T01:21:54.700+0000] {processor.py:161} INFO - Started process (PID=4686) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:54.702+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:21:54.703+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:21:54.703+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:54.740+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:21:54.737+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:21:54.742+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:21:54.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.068 seconds
[2025-02-16T01:22:24.964+0000] {processor.py:161} INFO - Started process (PID=4746) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:24.966+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:22:24.967+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:22:24.967+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:25.007+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:22:25.003+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:22:25.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:25.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.072 seconds
[2025-02-16T01:22:55.375+0000] {processor.py:161} INFO - Started process (PID=4807) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:55.376+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:22:55.377+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:22:55.377+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:55.408+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:22:55.405+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:22:55.410+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:22:55.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.063 seconds
[2025-02-16T01:23:25.823+0000] {processor.py:161} INFO - Started process (PID=4867) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:25.825+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:23:25.826+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:23:25.825+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:25.853+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:23:25.849+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:23:25.855+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:25.876+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.060 seconds
[2025-02-16T01:23:56.558+0000] {processor.py:161} INFO - Started process (PID=4925) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:56.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:23:56.564+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:23:56.563+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:56.629+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:23:56.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:23:56.631+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:23:56.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.115 seconds
[2025-02-16T01:24:27.204+0000] {processor.py:161} INFO - Started process (PID=4985) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:27.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:24:27.207+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:24:27.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:27.238+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:24:27.234+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:24:27.239+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:27.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.060 seconds
[2025-02-16T01:24:57.358+0000] {processor.py:161} INFO - Started process (PID=5045) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:57.359+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:24:57.360+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:24:57.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:57.392+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:24:57.388+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:24:57.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:24:57.414+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.064 seconds
[2025-02-16T01:25:28.176+0000] {processor.py:161} INFO - Started process (PID=5105) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:28.177+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:25:28.178+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:25:28.178+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:28.213+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:25:28.210+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:25:28.215+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:28.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:25:58.507+0000] {processor.py:161} INFO - Started process (PID=5165) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:58.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:25:58.509+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:25:58.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:58.542+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:25:58.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:25:58.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:25:58.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.063 seconds
[2025-02-16T01:26:28.663+0000] {processor.py:161} INFO - Started process (PID=5225) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:28.664+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:26:28.665+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:26:28.665+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:28.694+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:26:28.691+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:26:28.696+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:28.716+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.059 seconds
[2025-02-16T01:26:59.107+0000] {processor.py:161} INFO - Started process (PID=5285) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:59.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:26:59.109+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:26:59.109+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:59.134+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:26:59.131+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:26:59.136+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:26:59.156+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.056 seconds
[2025-02-16T01:27:29.293+0000] {processor.py:161} INFO - Started process (PID=5345) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:29.294+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:27:29.295+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:27:29.295+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:29.324+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:27:29.320+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:27:29.325+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:29.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.060 seconds
[2025-02-16T01:27:59.667+0000] {processor.py:161} INFO - Started process (PID=5405) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:59.668+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:27:59.670+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:27:59.669+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:59.705+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:27:59.702+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:27:59.707+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:27:59.727+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:28:30.084+0000] {processor.py:161} INFO - Started process (PID=5465) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:28:30.085+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:28:30.087+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:28:30.086+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:28:30.117+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:28:30.114+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:28:30.119+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:28:30.139+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.061 seconds
[2025-02-16T01:29:01.128+0000] {processor.py:161} INFO - Started process (PID=5525) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:01.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:29:01.132+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:29:01.131+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:01.164+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:29:01.160+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:29:01.166+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:01.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.069 seconds
[2025-02-16T01:29:31.874+0000] {processor.py:161} INFO - Started process (PID=5585) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:31.875+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:29:31.877+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:29:31.876+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:31.902+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:29:31.899+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:29:31.903+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:29:31.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.057 seconds
[2025-02-16T01:30:02.427+0000] {processor.py:161} INFO - Started process (PID=5645) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:02.428+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:30:02.429+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:30:02.429+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:02.467+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:30:02.463+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:30:02.469+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:02.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.074 seconds
[2025-02-16T01:30:33.017+0000] {processor.py:161} INFO - Started process (PID=5705) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:33.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:30:33.020+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:30:33.020+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:33.052+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:30:33.049+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:30:33.054+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:30:33.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.063 seconds
[2025-02-16T01:31:03.620+0000] {processor.py:161} INFO - Started process (PID=5765) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:03.621+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:31:03.622+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:31:03.622+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:03.657+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:31:03.653+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:31:03.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:03.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:31:33.980+0000] {processor.py:161} INFO - Started process (PID=5825) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:33.981+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:31:33.982+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:31:33.982+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:34.016+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:31:34.013+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:31:34.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:31:34.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:32:04.274+0000] {processor.py:161} INFO - Started process (PID=5885) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:04.275+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:32:04.276+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:32:04.276+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:04.317+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:32:04.312+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:32:04.319+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:04.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.077 seconds
[2025-02-16T01:32:35.109+0000] {processor.py:161} INFO - Started process (PID=5945) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:35.110+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:32:35.111+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:32:35.111+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:35.147+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:32:35.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:32:35.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:32:35.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:33:05.467+0000] {processor.py:161} INFO - Started process (PID=6005) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:05.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:33:05.469+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:33:05.469+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:05.497+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:33:05.494+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:33:05.499+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:05.520+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.060 seconds
[2025-02-16T01:33:35.839+0000] {processor.py:161} INFO - Started process (PID=6065) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:35.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:33:35.841+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:33:35.841+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:35.875+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:33:35.871+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:33:35.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:33:35.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.067 seconds
[2025-02-16T01:34:06.134+0000] {processor.py:161} INFO - Started process (PID=6125) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:06.135+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:34:06.137+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:34:06.136+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:06.174+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:34:06.168+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:34:06.176+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:06.197+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.069 seconds
[2025-02-16T01:34:37.110+0000] {processor.py:161} INFO - Started process (PID=6185) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:37.111+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:34:37.112+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:34:37.112+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:37.146+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:34:37.143+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:34:37.148+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:34:37.170+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.067 seconds
[2025-02-16T01:35:07.321+0000] {processor.py:161} INFO - Started process (PID=6245) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:07.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:35:07.324+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:35:07.324+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:07.355+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:35:07.350+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:35:07.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:07.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.066 seconds
[2025-02-16T01:35:37.740+0000] {processor.py:161} INFO - Started process (PID=6305) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:37.741+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:35:37.742+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:35:37.742+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:37.777+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:35:37.773+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:35:37.779+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:35:37.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.068 seconds
[2025-02-16T01:36:08.381+0000] {processor.py:161} INFO - Started process (PID=6365) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:08.382+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:36:08.384+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:36:08.383+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:08.423+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:36:08.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:36:08.425+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:08.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.078 seconds
[2025-02-16T01:36:38.558+0000] {processor.py:161} INFO - Started process (PID=6425) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:38.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:36:38.561+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:36:38.560+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:38.594+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:36:38.590+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
ImportError: cannot import name 'upload_bronze' from 'app.upload_bronze' (/opt/airflow/dags/app/upload_bronze.py)
[2025-02-16T01:36:38.596+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:36:38.616+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.064 seconds
[2025-02-16T01:37:08.991+0000] {processor.py:161} INFO - Started process (PID=6484) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:08.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:37:08.993+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:08.993+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:09.587+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:09.689+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.689+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:upload_bronze
[2025-02-16T01:37:09.700+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.699+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:upload_bronze
[2025-02-16T01:37:09.709+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.709+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:upload_bronze
[2025-02-16T01:37:09.710+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.710+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:37:09.724+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.724+0000] {dag.py:3118} INFO - Creating ORM DAG for upload_bronze
[2025-02-16T01:37:09.734+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:09.733+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:37:09.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.778 seconds
[2025-02-16T01:37:40.243+0000] {processor.py:161} INFO - Started process (PID=6544) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:40.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:37:40.246+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:40.246+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:40.835+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:37:40.852+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:40.851+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:37:40.869+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:37:40.869+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:37:40.888+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.653 seconds
[2025-02-16T01:38:11.186+0000] {processor.py:161} INFO - Started process (PID=6604) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:11.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:38:11.188+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:11.188+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:11.667+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:11.684+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:11.683+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:38:11.700+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:11.700+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:38:11.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.538 seconds
[2025-02-16T01:38:41.814+0000] {processor.py:161} INFO - Started process (PID=6665) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:41.815+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:38:41.816+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:41.816+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:42.328+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:38:42.345+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:42.344+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:38:42.369+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:38:42.369+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:38:42.387+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.580 seconds
[2025-02-16T01:39:12.492+0000] {processor.py:161} INFO - Started process (PID=6725) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:12.493+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:39:12.495+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:12.494+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:12.950+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:12.965+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:12.964+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:39:12.982+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:12.982+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:39:12.999+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.518 seconds
[2025-02-16T01:39:43.118+0000] {processor.py:161} INFO - Started process (PID=6784) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:43.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:39:43.120+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:43.120+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:43.709+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:39:43.733+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:43.732+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:39:43.756+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:39:43.756+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:39:43.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.672 seconds
[2025-02-16T01:40:14.774+0000] {processor.py:161} INFO - Started process (PID=6845) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:14.776+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:40:14.778+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:14.778+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:15.279+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:15.296+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:15.296+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:40:15.319+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:15.318+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:40:15.338+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.571 seconds
[2025-02-16T01:40:46.108+0000] {processor.py:161} INFO - Started process (PID=6907) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:46.109+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:40:46.111+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:46.110+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:46.681+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:40:46.699+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:46.699+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:40:46.720+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:40:46.720+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:40:46.743+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.642 seconds
[2025-02-16T01:41:16.912+0000] {processor.py:161} INFO - Started process (PID=6969) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:16.913+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:41:16.914+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:16.914+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:17.430+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:17.446+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:17.446+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:41:17.465+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:17.464+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:41:17.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.581 seconds
[2025-02-16T01:41:48.204+0000] {processor.py:161} INFO - Started process (PID=7029) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:48.205+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:41:48.207+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:48.206+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:48.710+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:41:48.725+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:48.725+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:41:48.742+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:41:48.741+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:41:48.759+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.562 seconds
[2025-02-16T01:42:18.928+0000] {processor.py:161} INFO - Started process (PID=7089) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:18.929+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:42:18.931+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:18.930+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:19.497+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:19.516+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:19.515+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:42:19.535+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:19.535+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:42:19.554+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.635 seconds
[2025-02-16T01:42:49.955+0000] {processor.py:161} INFO - Started process (PID=7149) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:49.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:42:49.957+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:49.957+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:51.566+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:42:51.590+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:51.590+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:42:51.622+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:42:51.622+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:42:51.647+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 1.699 seconds
[2025-02-16T01:43:22.251+0000] {processor.py:161} INFO - Started process (PID=7212) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:22.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:43:22.253+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:22.253+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:22.872+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:22.890+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:22.889+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:43:22.911+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:22.911+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:43:22.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.691 seconds
[2025-02-16T01:43:53.166+0000] {processor.py:161} INFO - Started process (PID=7276) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:53.167+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:43:53.169+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:53.168+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:53.680+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:43:53.696+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:53.695+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:43:53.713+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:43:53.713+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:43:53.731+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.572 seconds
[2025-02-16T01:44:24.481+0000] {processor.py:161} INFO - Started process (PID=7336) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:24.482+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:44:24.483+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:24.483+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:24.839+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:24.859+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:24.859+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:44:24.879+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:24.879+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:44:24.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.424 seconds
[2025-02-16T01:44:55.046+0000] {processor.py:161} INFO - Started process (PID=7399) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:55.048+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:44:55.049+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:55.048+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:55.754+0000] {processor.py:840} INFO - DAG(s) 'upload_bronze' retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:44:55.772+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:55.772+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-02-16T01:44:55.796+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:44:55.796+0000] {dag.py:3954} INFO - Setting next_dagrun for upload_bronze to 2025-02-15 00:00:00+00:00, run_after=2025-02-16 00:00:00+00:00
[2025-02-16T01:44:55.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.779 seconds
[2025-02-16T01:45:25.959+0000] {processor.py:161} INFO - Started process (PID=7470) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:25.961+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:45:25.962+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:45:25.961+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:26.354+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:45:26.339+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:45:26.356+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:26.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.424 seconds
[2025-02-16T01:45:56.610+0000] {processor.py:161} INFO - Started process (PID=7530) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:56.612+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:45:56.613+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:45:56.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:57.076+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:45:57.062+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:45:57.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:45:57.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.494 seconds
[2025-02-16T01:46:27.237+0000] {processor.py:161} INFO - Started process (PID=7590) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:27.239+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:46:27.240+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:46:27.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:27.578+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:46:27.564+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:46:27.580+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:27.599+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.368 seconds
[2025-02-16T01:46:57.706+0000] {processor.py:161} INFO - Started process (PID=7642) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:57.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:46:57.708+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:46:57.708+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:58.085+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:46:58.076+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:46:58.087+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:46:58.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.405 seconds
[2025-02-16T01:47:28.541+0000] {processor.py:161} INFO - Started process (PID=7702) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:47:28.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:47:28.543+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:47:28.543+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:47:29.241+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:47:29.231+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:47:29.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:47:29.260+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.726 seconds
[2025-02-16T01:47:59.415+0000] {processor.py:161} INFO - Started process (PID=7767) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:47:59.416+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:47:59.417+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:47:59.417+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:48:00.356+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:48:00.341+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:48:00.359+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:48:00.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 0.980 seconds
[2025-02-16T01:48:47.990+0000] {processor.py:161} INFO - Started process (PID=7819) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:48:47.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:48:47.993+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:48:47.992+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:52:00.176+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:52:00.122+0000] {timeout.py:68} ERROR - Process timed out, PID: 7819
[2025-02-16T01:52:32.623+0000] {processor.py:161} INFO - Started process (PID=7881) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:52:32.626+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:52:32.627+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:52:32.626+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:52:33.762+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:52:33.739+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:52:33.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:52:33.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 1.260 seconds
[2025-02-16T01:56:12.359+0000] {processor.py:161} INFO - Started process (PID=7925) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:56:12.361+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T01:56:12.364+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:56:12.363+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:56:17.637+0000] {logging_mixin.py:188} INFO - [2025-02-16T01:56:17.623+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T01:56:17.640+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T01:56:17.664+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 5.333 seconds
[2025-02-16T02:03:43.915+0000] {processor.py:161} INFO - Started process (PID=7974) to work on /opt/airflow/dags/Dag_des_5.py
[2025-02-16T02:03:43.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/Dag_des_5.py for tasks to queue
[2025-02-16T02:03:43.918+0000] {logging_mixin.py:188} INFO - [2025-02-16T02:03:43.917+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T02:03:45.074+0000] {logging_mixin.py:188} INFO - [2025-02-16T02:03:45.062+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/Dag_des_5.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/Dag_des_5.py", line 5, in <module>
    from app.upload_bronze import upload_bronze
  File "/opt/airflow/dags/app/upload_bronze.py", line 16, in <module>
    upload_bronze()
  File "/opt/airflow/dags/app/upload_bronze.py", line 11, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\Dados'
[2025-02-16T02:03:45.076+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/Dag_des_5.py
[2025-02-16T02:03:45.104+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/Dag_des_5.py took 1.202 seconds
