[2025-02-25T00:41:14.706+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-25T00:41:14.727+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:31:07.373453+00:00 [queued]>
[2025-02-25T00:41:14.735+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:31:07.373453+00:00 [queued]>
[2025-02-25T00:41:14.736+0000] {taskinstance.py:2303} INFO - Starting attempt 3 of 6
[2025-02-25T00:41:14.751+0000] {taskinstance.py:2327} INFO - Executing <Task(PythonOperator): upload_bronze> on 2025-02-25 00:31:07.373453+00:00
[2025-02-25T00:41:14.758+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=479) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-25T00:41:14.760+0000] {standard_task_runner.py:63} INFO - Started process 481 to run task
[2025-02-25T00:41:14.760+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'upload_bronze', 'upload_bronze', 'manual__2025-02-25T00:31:07.373453+00:00', '--job-id', '53', '--raw', '--subdir', 'DAGS_FOLDER/Dag_des_5.py', '--cfg-path', '/tmp/tmpv2sdklmd']
[2025-02-25T00:41:14.761+0000] {standard_task_runner.py:91} INFO - Job 53: Subtask upload_bronze
[2025-02-25T00:41:14.810+0000] {task_command.py:426} INFO - Running <TaskInstance: upload_bronze.upload_bronze manual__2025-02-25T00:31:07.373453+00:00 [running]> on host c37e8af922b1
[2025-02-25T00:41:14.902+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='upload_bronze' AIRFLOW_CTX_TASK_ID='upload_bronze' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:31:07.373453+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-25T00:31:07.373453+00:00'
[2025-02-25T00:41:14.904+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-25T00:41:14.905+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-25T00:41:14.906+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/app/upload_bronze.py", line 12, in upload_bronze
    for file in os.listdir(INPUT_DIR):
                ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\RID-156732_Desafio08\\Airflow\\dags\\app\\Dados'
[2025-02-25T00:41:14.922+0000] {taskinstance.py:1205} INFO - Marking task as UP_FOR_RETRY. dag_id=upload_bronze, task_id=upload_bronze, execution_date=20250225T003107, start_date=20250225T004114, end_date=20250225T004114
[2025-02-25T00:41:14.936+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 53 for task upload_bronze ([Errno 2] No such file or directory: 'C:\\Users\\Caio Mesquita\\Desktop\\Data sc\\Des_5\\RID-156732_Desafio08\\Airflow\\dags\\app\\Dados'; 481)
[2025-02-25T00:41:14.978+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-02-25T00:41:15.001+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-25T00:41:15.004+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
